[browser]
gatherUsageStats = false

[server]
enableCORS = false
enableXsrfProtection = false
headless = true

[theme]
base = "dark"
primaryColor = "#FFB84D"
backgroundColor = "#0A0D11"
secondaryBackgroundColor = "#141920"
textColor = "#E0E0E0"
font = "sans serif"
